### ISSUE TITLE
Camel cased properties do not receive units as defined in the units option for a custom styler

### ISSUE THREAD

**Issue by JonKelley88** [immutabl3/to-style#1]
The omission of a value unit only appears to happen when overriding the default units in a custom styler and when passing it properties that are camel cased such as `font-size`

```js
const myStyler = toStyle.create({
     transform3d: false,
     units: {
          fontSize: '%',
     }
});

const test = myStyler({
     fontSize: 100
}); 

console.log(test);
// expected output - { fontSize: 100% }
// actual output - { fontSize: 100 }
```

**Comment by JosephClay** [comment]
An extra step has been added before passing through the value to look for user-defined precision and units in version `1.1.0` along with unit tests
